### ISSUE TITLE
[REQ]Cpp14 compliance

### ISSUE THREAD

**Issue by d-wang03** [bshoshany/thread-pool#109]
**Describe the new feature**

Since the cpp14 is used more widely especially on embedded devices, I suggest make the thread pool to compliant with it.
Here is the patch, that I tried to port the thread pool lite, and get no errors and all test cases in BS_thread_pool_light_test.cpp passed.
Could you review it, and merge it in future?
[cpp14.patch](https://github.com/bshoshany/thread-pool/files/11512905/cpp14.patch)

**Comment by bshoshany** [comment]
Thanks for the suggestion! However, the title of the project is "BS::thread_pool: a fast, lightweight, and easy-to-use <b><ins>C++17</ins></b> thread pool library". Therefore, it is only meant to be compatible with C++17 or later. I do not have any plans to make it backwards-compatible with C++14 or older versions, now or in the future.  Your patch might work (although I haven't tested it), but it makes the code longer and less elegant, and in the future I might want to use other C++17 features that cannot be backported like this.
