### ISSUE TITLE
[REQ] cpuaff integration

### ISSUE THREAD

**Issue by yanzixiang** [bshoshany/thread-pool#113]
**cpuaff integration**
the lib make all the threads private,
Is it possible to give the user the opportunity to make some modify to the threads ?
i want to make Multiple Thread Pools,
as if one pool bind to core 1,2,
and another pool bind to core 3,4,
so that i can push task to the binded core

**Code example**
```cpp
BS::thread_pool thread_pool;

cpuaff::cpu_set new_affinity;

thread_pool.set_new_affinity(new_affinity);
```

**Additional information**

http://dcdillon.github.io/cpuaff/

https://github.com/bshoshany/thread-pool/issues/37

**Comment by bshoshany** [comment]
What you're asking for seems to be similar to #105, which is planned to be implemented in the next release.
