### ISSUE TITLE
How to create a thread pool for infinite execution ?

### ISSUE THREAD

**Issue by d3hydr8** [bshoshany/thread-pool#116]
I have few tasks like Task1, Task2 and Task3. I want these tasks to execute in an infinite loop and also need to take care that the threads are consuming less CPU. Is there any solution for that ? Thanks a lot in advance.

Example:

void main(){

BS::thread_pool pool;
while(true){
pool.push_task(Task1);
pool.push_task(Task2);
pool.push_task(Task3);
}
}
I want all tasks to reuse the same thread and invoke automatically again from Task1 when Task3 gets completed without using spinlock or infinite while loop

**Comment by bshoshany** [comment]
Sorry, I'm not really sure what you're trying to do here. Generally you should never use infinite loops and/or submit an infinite number of tasks to the pool, especially not without waiting for the tasks to finish before you post more. Please see the documentation for examples of proper use of the thread pool. If you have any further questions, please post on StackOverflow or StackExchange Code Review. Good luck!
