### ISSUE TITLE
[REQ] Run function on all threads

### ISSUE THREAD

**Issue by lgs-baada** [bshoshany/thread-pool#119]
**Describe the new feature**

Run a function on all threads when creating (or changing) the thread pool.

**Code example**

```cpp
BS::thread_pool pool([] { nice(1); });
```

Or:

```cpp
BS::thread_pool pool(12, [] { nice(1); });
```

Or:

```cpp
BS::thread_pool pool([] (auto id) {
    const auto name = std::format("worker{}", id);
    pthread_setname_np(pthread_self(), name.c_str());
});
```

**Additional information**

This feature can be used to change settings of the threads (priority, name, etc.).

**Comment by bshoshany** [comment]
Thank you for this feature request! This has already been requested in #105, and is set to be incorporated in the next release (which may be in a couple of months).
