### ISSUE TITLE
Thread priority class

### ISSUE THREAD

**Issue by IlTeo285** [bshoshany/thread-pool#122]
It's very useful to be able to set the thread priority class. In a general sense, this can be achieved by exposing the native handles to the caller like this.
```cpp
    [[nodiscard]] std::vector<std::thread::native_handle_type> get_threads_raw_handle() const
    {
        std::vector<std::thread::native_handle_type> raw_hndls;
        for (concurrency_t i = 0; i < thread_count; ++i)
        {
            raw_hndls.push_back(threads[i].native_handle());
        }

        return raw_hndls;
    }
```

Another approach could be to accept a user callback to be called during the thread creation phase.

**Comment by bshoshany** [comment]
Thanks for the suggestion! This looks like it might be useful. I will add it (with slight changes and an example in the documentation) to v3.6.0, which should be available within the next few weeks.
