### ISSUE TITLE
[REQ] worker keeps its task alive for longer than required

### ISSUE THREAD

**Issue by Iunave** [bshoshany/thread-pool#124]
By declaring the std::function<void()> task outside the scope of the worker loop the task is kept alive until the worker acquires the next task to process. This is both unnecessary and is prone to unexpected behavior for code that expects its task to be destroyed once it has finished executing. eg: binding a shared pointer to the task object.
The fix is really simple, just move the std::function<void()> task to where it is assigned.

**how the new worker function would look like**
```cpp
    void worker()
    {
        while (true)
        {
            std::unique_lock tasks_lock(tasks_mutex);
            task_available_cv.wait(tasks_lock, [this] { return !tasks.empty() || !workers_running; });
            if (!workers_running)
                break;
            if (paused)
                continue;
            std::function<void()> task = std::move(tasks.front());
            tasks.pop();
            ++tasks_running;
            tasks_lock.unlock();
            task();
            tasks_lock.lock();
            --tasks_running;
            if (waiting && !tasks_running && (paused || tasks.empty()))
                tasks_done_cv.notify_all();
        }
    }
```

**Comment by bshoshany** [comment]
Hi @Iunave and thanks for opening this issue! This seems like an easy enough change. I will implement it in v3.6.0, to be released within the next few weeks.
