### ISSUE TITLE
Support Task Prepending (executing higher priority tasks first)

### ISSUE THREAD

**Issue by Oberonc** [bshoshany/thread-pool#135]
Suppose there is a situation where I want to submit a high priority task (to be executed before normal priority tasks).
The current API doesnt support that and the backend container (std::queue) doesnt support that.

I suggest switching to a std:deque and adding API functions for submitting (or attaching) tasks to the front of the queue to be executed ASAP.

**Comment by bshoshany** [comment]
Thanks for opening this issue! However, v4.0.0, which was released yesterday, already offers a priority queue. Please see the documentation for details.
