### ISSUE TITLE
[REQ] does this library support recursive/nested tasks? 

### ISSUE THREAD

**Issue by wkjarosz** [bshoshany/thread-pool#142]
I did not see this mentioned in the documentation (sorry if I missed it).

Does this library support nested or recursive tasks without deadlock/thread starvation? 

For instance, I need to perform 10 tasks, which can be done independently, but within each tasks, I might have several loops that I would like to parallelize as well. If I use `submit_loop` or similar within each of these 10 tasks, do I run the risk of the inner loops never making progress because all threads in the pool are already allocated to the outer set of 10 tasks?

My understanding is that with this library, the calling thread never steps in to make progress on a task or loop if the threadpool is full, which means deadlock could indeed happen with the above type of workload structure.

Thanks

**Comment by wkjarosz** [comment]
Thanks for the info and suggested workarounds. Unfortunately, this probably means BS::thread_pool is not the right design for my needs, so i'll likely go in a different direction. Thanks again.

**Comment by wkjarosz** [comment]
There are threadpool designs that can avoid issues with recursive tasks or one task depending on the completion of another in the same pool. You can check out the following two resources:

https://maxliani.wordpress.com/2022/07/27/anatomy-of-a-task-scheduler/
https://github.com/mitsuba-renderer/nanothread

One way to enable this is to ensure that wait-type functions don't just wait, but have the calling thread step into and execute tasks from the thread pool (incidentally, this also allows the thread pool to have a size of zero where no additional threads are ever launched).

**Comment by bshoshany** [comment]
Thanks, I will take a look.
