### ISSUE TITLE
[REQ] need a uninit_task parameter for thread_pool

### ISSUE THREAD

**Issue by debuggingbug** [bshoshany/thread-pool#152]
**Describe the new feature**

Now only has init_task, better has uninit_task.

**Code example**

```cpp
BS::thread_pool task_thread_{1,
                             [] {
                                 ::CoInitializeEx(nullptr, COINIT_APARTMENTTHREADED);
                             },
                             [] { CoUninitialize(); }};
```

**Additional information**

**Comment by bshoshany** [comment]
Hi @debuggingbug and thanks for opening this issue! This seems like a good idea. I will implement it in the next release.
