### ISSUE TITLE
[REQ]Allow to measure the threads idle time

### ISSUE THREAD

**Issue by rapastranac** [bshoshany/thread-pool#157]
**Describe the new feature**

A total amount of idle time would be necessary for usages where CPU utilization is the main target of this thread pool. For applications that use this pool where the goal is to achieve massive parallelization, 100% of CPU utilization is something sought to make the most of computing power. This would serve only for statistic purposes for whoever uses it.  This idle time is reset along with the already reset() method.

**Comment by bshoshany** [comment]
Hi @rapastranac and thanks for opening this issue! I can see that you also opened PR #158, so I will respond there.
