### ISSUE TITLE
It would be better to provide some unit tests.

### ISSUE THREAD

**Issue by trevor211** [bshoshany/thread-pool#16]
As far as I know, there are 2 benifits if you would provide unit tests:

1. Confidence: with all the use cases tested, provider would be more confident with the code.
2. Convenience: it would be convenient for users to refer to the test cases while using the code.

**Comment by bshoshany** [comment]
Thanks for the suggestion! I will add a `.cpp` file to the repository that performs automated tests of each of the package's features in a future release, but probably not before September, since I have a very busy summer.

**Comment by zeroset** [comment]
I think you should provide some examples and unittests. Especially you should think about automatically executing the tests, maybe in github actions. Unfortunately i am not sure about the available parallelism in github actions. ref [joss-review](https://github.com/openjournals/joss-reviews/issues/3291)

**Comment by simsong** [comment]
I am now using `thread-pool` on a soon-to-be-production system. I am creating unit tests and code coverage reported on codecov.io. If you wish, I can send pull requests to this repo with some of them.

**Comment by bshoshany** [comment]
@simsong glad to know that you are using this library in your system! Thanks so much for your suggestion. I would prefer to write my own unit tests (it will be good practice), but I would love to see your unit tests for guidance, if you are willing to provide a link!

**Comment by bshoshany** [comment]
Unit tests are now provided in v2.0.0! Please see `thread_pool_test.cpp`. I am closing this issue, but if you find any problems with the tests, please open a separate issue.
