### ISSUE TITLE
[BUG] std::thread::hardware_concurrency() should not be used on Linux

### ISSUE THREAD

**Issue by jbd** [bshoshany/thread-pool#161]
Hello,

[this is similar to https://github.com/mhx/dwarfs/issues/130]

std::thread::hardware_concurrency() returns, when possible, the underlying hardware capability to run threads, which might not corresponds to the actual number of cores available to the process (through the use of taskset, batch system like slurm, etc...). The consequence is that the thread pool might run in a non optimal way. For example, if I run taskset -c 1 myprogram on my 20 cores machines, it will run 20 workers on only one core.

Consider this code run through the slurm scheduler using srun, requesting 4 cores:

```
#include <iostream>
#include <sched.h>
#include <thread>  
 
int main (void) {
    cpu_set_t cpu_set;
    int cores = std::thread::hardware_concurrency();
    std::cout << "using std::thread::hardware_concurrency: " << cores << "\n";
    sched_getaffinity(0, sizeof(cpu_set), &cpu_set);
    cores = CPU_COUNT(&cpu_set);
    std::cout << "using sched_getaffinity: " << cores << "\n";
    return 0;
}
```

```
$ srun -c 4 ./get_cores
srun: job 13694693 queued and waiting for resources
srun: job 13694693 has been allocated resources
using std::thread::hardware_concurrency: 96
using sched_getaffinity: 4
```

I think a more sane behavior for thread-pool would be to use sched_getaffinity as in the folly library for example (`folly/folly/system/HardwareConcurrency.cpp`)

```
#include <folly/system/HardwareConcurrency.h>

#include <thread>

#include <folly/portability/Sched.h>

namespace folly {

unsigned int hardware_concurrency() noexcept {
#if defined(__linux__) && !defined(__ANDROID__)
  cpu_set_t cpuset;
  if (!sched_getaffinity(0, sizeof(cpuset), &cpuset)) {
    auto count = CPU_COUNT(&cpuset);
    if (count != 0) {
      return count;
    }
  }
#endif

  return std::thread::hardware_concurrency();
}

} // namespace folly
```

What do you think ?

Thank you for considering this change, and especially thank you for this fantastic library.

Jean-Baptiste

**Comment by bshoshany** [comment]
Hi @jbd and thanks for opening this issue!

I think the problem you are raising is actually not Linux-specific; most major operating systems (except macOS) have a notion of processor affinity. The hardware concurrency is constant, while the affinity may be determined per process.

Of course, one of the main guiding principles in developing this library is portability - using only the C++ standard library, and not relying on OS-specific features. However, in v5.0.0 I added the native extensions, which among other things offer the function `BS::get_os_process_affinity()` which, on Windows or Linux, will return the affinity of the current process.

So you can easily get the total number of processors available to your process in a fully portable way (without any native API calls) like this:

```cpp
#define BS_THREAD_POOL_NATIVE_EXTENSIONS
#include "BS_thread_pool.hpp"

int main()
{
    const std::optional<std::vector<bool>> affinity = BS::get_os_process_affinity();
    const std::size_t num_threads = affinity ? std::ranges::count(*affinity, true) : std::thread::hardware_concurrency();
    BS::thread_pool pool(num_threads);
    std::cout << "Number of available threads: " << pool.get_thread_count() << '\n';
}
```

I will see about adding a feature to the upcoming v5.1.0 that will do this automatically if the pool is created without specifying the number of threads, if the native extensions are enabled. (If the native extensions are disabled, then the library only uses standard C++.)

Thanks again for this suggestion! I'm glad to hear that you find the library useful :)
