### ISSUE TITLE
Less copy in push_task?

### ISSUE THREAD

**Issue by gelldur** [bshoshany/thread-pool#24]
```
    template <typename F>
    void push_task(const F &task)
```

Maybe it would be better to forward reference or move? If no then why :) ?

**Comment by bshoshany** [comment]
Hi and thanks for opening the issue! Would you mind providing more details about what it is exactly that you think should be changed and why?

**Comment by gelldur** [comment]
make less copy on `F`. Refer to:
https://github.com/bshoshany/thread-pool/blob/b6cd773f37b1be7718f771ae7403726a28be5f40/thread_pool.hpp#L172

E.g.
```
    template <typename F>
    void push_task(F task)
    {
        tasks_total++;
        {
            const std::scoped_lock lock(queue_mutex);
            tasks.push(std::function<void()>(std::move(task)));
        }
    }
```

Same for forwarding `Args...` etc.

**Comment by bshoshany** [comment]
Sorry, but I'm confused. In my version I'm taking `task` as a constant reference, hence there is no copying. In your version you take `task` by value, so it is actually your version where copying is performed... I'm closing this issue.

**Comment by AeanSR** [comment]
> Sorry, but I'm confused. In my version I'm taking `task` as a constant reference, hence there is no copying. In your version you take `task` by value, so it is actually your version where copying is performed... I'm closing this issue.

Taking by value may avoid a copy vs taking by cref, since C++17 requires mandatory copy elision. Consider calling with a lambda (a [prvalue](https://en.cppreference.com/w/cpp/language/value_category#prvalue)), say `push_task([](){})`.

* In your original code,
    * the lambda is [bound from a const lvalue reference, thus a temporary materialization is required.](https://en.cppreference.com/w/cpp/language/implicit_conversion#Temporary_materialization) `task` is initialized as a temporary to become _lvalue_.
    * Construction of the `std::function<void()>`. The result is _prvalue_.
    * The _prvalue_ functor is moved into the queue, the _rvref_ overloading of [push](https://en.cppreference.com/w/cpp/container/queue/push) is selected by overload resolution due to being called with a _prvalue_ of the same type. 
    * *Summary:* The lambda is materialized first, then used to construct the functor directly on the queue. There is 1 copy of the temporarily materialized lambda.
* In @gelldur version,
    * the parameter `task` is initialized with a _prvalue_ of the same type `F = <unamed lambda>`. This triggers the guaranteed [copy elision](https://en.cppreference.com/w/cpp/language/copy_elision) by standard, thus the lambda `[](){}` is not materialized, i.e., no data is copied to initialize `task`.
    * Template parameters are _prvalue_ *unless defined as _lvalue_ references* (exactly as what the original code does).
    * A _prvalue_ `task` is moved from, thus triggering a conversion to an _xvalue_. A non-mandatory move elision may occur (depends on the compiler).
    * Move constructing the `std::function<void()>`, which is a _prvalue_ again.
    * The _prvalue_ functor is moved into the queue, the _rvref_ overloading of [push](https://en.cppreference.com/w/cpp/container/queue/push) is selected by overload resolution due to being called with a _prvalue_ of the same type. 
    * *Summary:* If the compiler performs move elision, there are 0 copies, and the functor is initialized directly on the queue. However, the compiler is not required to perform the move elision. In that case, there is 1 copy of the temporarily materialized lambda.

However, I think the `std::move` in @gelldur version is misused and should be `std::forward<F>`. `task` will not be forced to convert from _prvalue_ to _xvalue_ by using `std::forward`, so we can leverage the mandatory elision guaranteed by the standard. There will be 0 copies then.

IMO with C++17, one should try to avoid using crefs except really necessary. The crefs force every expression to be _lvalue_, materialized somewhere in the memory, resulting in more copying. Counterintuitive for old-style C++ programmers though.

Correct me if I am wrong.

**Comment by bshoshany** [comment]
Thanks for this in-depth analysis, @AeanSR. There are some subtleties here that I don't fully understand at the moment, but I'll look into it. In any case, I have a huge list of changes to make in this library that are of higher priority, so it might take some time before I get to it.
