### ISSUE TITLE
Add explicit to single-parameter constructors

### ISSUE THREAD

**Issue by NewbieOrange** [bshoshany/thread-pool#28]
**Describe the new feature**

Can we add explicit to single-parameter constructors to avoid unintended implicit construct?

**Code example**

```cpp
    explicit thread_pool(const ui32 &_thread_count = std::thread::hardware_concurrency())
        : thread_count(_thread_count ? _thread_count : std::thread::hardware_concurrency()), threads(new std::thread[thread_count]);
// ...
    explicit synced_stream(std::ostream &_out_stream = std::cout);
```

**Comment by bshoshany** [comment]
Thanks for the suggestion! I'm not opposed to adding the `explicit` keyword, but given that there is only one constructor for each of these classes, under what circumstances will implicit constructors be an issue?

**Comment by NewbieOrange** [comment]
To disallow passing an `uint32` to a function taking, for example, `thread_pool` as a const ref, therefore forcing users to explicitly call the constructor to avoid confusion or unintended object construction.

**Comment by bshoshany** [comment]
I'm still not convinced. Would you mind writing a short code example illustrating a case where this might be relevant? Thanks!

**Comment by NewbieOrange** [comment]
It may be a silly error, but: 

```cpp
std::size_t thread_cnt = 10;
thread_pool thread_pool{thread_cnt};

void f(const thread_pool& pool) {
  // do something
}

f(thread_cnt); // error-prone, passed wrong parameter but still compiles

```

**Comment by bshoshany** [comment]
Okay, I see what you mean. I'll add this to my TODO list, but it will only be added when the new version is released (which will have many other changes and new features). It might take a few weeks or even months since I'm really busy these days with teaching and research. Thanks for your contribution!
