### ISSUE TITLE
How to detect the number of physic cores?

### ISSUE THREAD

**Issue by nguyenpham** [bshoshany/thread-pool#29]
My computer has 4 physic/real cores and 4 virtual ones. The thread-pool auto-detects and initializes with 8 threads. However, my program runs some heavy computing tasks which are suitable to run on real cores only. 8 threads are significantly slower than 4 threads.

My question: is there any way to detect and set thread-pool to run with the number of physic/real cores only?

**Comment by bshoshany** [comment]
Unfortunately, the C++ standard does not offer this functionality. It only offers [`std::thread::hardware_concurrency`](https://en.cppreference.com/w/cpp/thread/thread/hardware_concurrency) which does not distinguish between physical cores and threads in a hyperthreaded CPU.

If you're only running the code on your own computer, you can just call the constructor with the number 4 in the argument. If other people are running your compiled program then you can allow the user to specify the desired number of threads, e.g. as a command-line argument.

**Comment by Nelson-numerical-software** [comment]
not easy to know numbers of hardware cores on all platforms. 
here a example 
https://github.com/Nelson-numerical-software/nelson/blob/master/modules/core/src/cpp/ComputionalThreads.cpp
