### ISSUE TITLE
[REQ] Passing thread_pool as parameters?

### ISSUE THREAD

**Issue by YulongNiu** [bshoshany/thread-pool#36]
**Describe the new feature**

Passing thread_pool as parameters in recursion. 

**Code example**

For the example bellow, I want to parallel the `chain` operation in multiple threads. Each "parent" chain object will generate two "children",  `next` and `update`, until `quick` element in each object is equal to 0. After `next` and `update` are produced, the parent can be destroyed. I want to put `next` and `update` to the thread pool, like I awkwardly described in `ChainReact()`. 

The basic process is like:
`start` --> `start_n` (from `start.next()`) and `start_u` (from `start.update()`), then throw them to the thread pool and destroy `start`.

`start_n` --> `start_n_n` and `start_n_u`, then throw them to thread pool and destroy `start_n`.
`start_u` --> `start_u_n` and `start_u_u`, then throw them to thread pool and destroy `start_u`.
...

I give a silly example below, but I can not compile it.  Please feel free to modify it, or correct me if I misused the `thread-pool`. 

```cpp
#include <iostream>

#include "thread-pool/thread_pool.hpp"

using namespace std;

class chain {
public:
  chain(const int quick, const int slow) : quick{ quick }, slow{ slow } {}

  int get_quick() const { return quick; }
  int get_slow() const { return slow; }

  chain next() const {
    chain elem{ quick / 2, slow };
    return elem;
  }

  chain update() const {
    chain elem{ (quick + slow) / 2, slow > 0 ? slow - 1 : 0 };
    return elem;
  }

  void print() const {
    cout << "quick is: " << quick << "; slow is: " << slow << endl;
  }

private:
  const int quick, slow;
};


void ChainReact(const chain& start, const thread_pool& tpool) {
  if (start.get_quick() == 0) {
    cout << "End reaction." << endl;
  } else {
    chain nchain = start.next();
    tpool.push_task(ChainReact, nchain, tpool);

    chain uchain = start.update();
    tpool.push_task(ChainReact, uchain, tpool);
  }

  if (tpool.get_tasks_total() == 0) { return; }
}


int main() {

  thread_pool pool;

  cout << "#threads: " << pool.get_thread_count() << endl;

  chain start{ 4, 20 };
  start.next().print();
  start.update().print();

  ChainReact(start, pool);

  return 0;
}
```

**Comment by bshoshany** [comment]
Sorry, to be honest I'm not exactly sure what you're trying to do here, but perhaps if you defined the thread pool as a global variable, or put everything inside one class with a static `thread_pool` variable, then you could avoid passing the thread pool as an argument to itself?

**Comment by YulongNiu** [comment]
I tried `v3.0.0`, and it works.

```c++
BS::thread_pool   pool;

void ChainReactParallel(const chain& start) {
  if (start.get_quick() == 0) {
    cout << "End reaction." << endl;
  } else {
    auto nchain = pool.submit(&chain::next, &start).get();
    ChainReactParallel(nchain);

    auto uchain = pool.submit(&chain::update, &start).get();
    ChainReactParallel(uchain);
  }
}
```
