### ISSUE TITLE
[BUG] Multiple Thread Pools

### ISSUE THREAD

**Issue by J-B-Blankenship** [bshoshany/thread-pool#37]
**Describe the bug**

Instantiating multiple thread pools throughout a code base causes issues when attempting to perform operations on said thread pools.

**Minimal working example**

Just allocate two thread_pool objects on the stack in different objects (also on the stack) and try to use them.

```cpp
```

**Behavior**

No crashes.

**System information**

* CPU model, architecture, # of cores and threads: i7-10875H x 16
* Operating system: Ubuntu 21.10
* Name and version of C++ compiler: gcc 11.2
* Full command used for compiling, including all compiler flags: Bazel's -c opt for C++20
* Thread pool library version: Latest

(Please note that only the latest version of the thread pool library is supported.)

**Additional information**

Include any additional information here.

**Comment by bshoshany** [comment]
Thanks for the bug report! I wrote a short test program that allocates two thread pools and pushes different tasks to each pool, and did not encounter any issues. Please provide a minimal working example that reproduces the bug.
