### ISSUE TITLE
[TEST] thread_pool_test.cpp

### ISSUE THREAD

**Issue by brunolnetto** [bshoshany/thread-pool#39]
**System information**

* CPU model, architecture, # of cores and threads:
11th Gen Intel® Core™ i7-11390H @ 3.40GHz × 8 

* Operating system:
Ubuntu 20.04.4 LTS

* Name and version of C++ compiler:
GCC 9.4.0

* Full command used for compiling, including all compiler flags:
gcc -Wall -Wpedantic -Wextra -Wconversion -Weffc++ thread_pool_test.cpp 

* Thread pool library version:
latest

**Log file**

http://codepad.org/uwXjtRzH

**Comment by bshoshany** [comment]
You forgot to add the `-std=c++17` flag.

**Comment by brunolnetto** [comment]
Do you mean `gcc -Wall -Wpedantic -Wextra -Wconversion -Weffc++ -std=c++17 thread_pool_test.cpp` ? I still receive many errors...

http://codepad.org/PtgUzwfa

**Comment by bshoshany** [comment]
Sorry, I have no idea why you're getting all these errors. Did you make any changes to the code? If so, please compile the original source code from the GitHub repository and see if that works. If not, I would recommend reinstalling GCC, as some of its files may be missing or corrupted. I tested the library using GCC 9.4.0 on CentOS Linux 7.6.1810 and had no issues.

**Comment by brunolnetto** [comment]
May you instruct me on how do I rebuild it from the repository?

**Comment by bshoshany** [comment]
Just download the repository, extract it to an empty folder, and then compile the `.cpp` file.

**Comment by brunolnetto** [comment]
By compilation, do you mean "Run the command on [post comment](https://github.com/bshoshany/thread-pool/issues/39#issuecomment-1100904279)"

**Comment by bshoshany** [comment]
No. As I said, you need to compile with the `-std=c++17` flag. The full command will be:

```
gcc thread_pool_test.cpp -std=c++17 -o thread_pool_test
```

You can add warning flags if you want to, but they are not necessary to compile the program.

**Comment by brunolnetto** [comment]
I did as you said: 

1. Download the [latest release zip file](https://github.com/bshoshany/thread-pool/releases);
2. Unzip in some folder;
3. Open terminal and navigate to the folder;
4. Run command `gcc thread_pool_test.cpp -std=c++17 -o thread_pool_test`

I still receive this zillions of errors: http://codepad.org/yloo9wPh

**Comment by bshoshany** [comment]
I'm sorry, unfortunately I have no idea why you're getting these errors :( I suggest trying a newer version of GCC or a different compiler altogether (e.g. Clang). If that doesn't work either, please ask for help on StackOverflow.

**Comment by AlexanderSerov** [comment]
Hi @brunolnetto 
I try to reproduce issue myself and indeed it's not compiled with suggested command. The errors supplied by you in codepad point out that it missed c++ standard library symbols which must be linked by default. Changing `gcc` to `g++` made the trick (read about difference on stackoverflow). And one more flag to compiler required `-pthread`
Full command:
`g++ thread_pool_test.cpp -std=c++17 -pthread -o thread_pool_test`

**Comment by bshoshany** [comment]
LOL, I'm a total idiot! 😅 I didn't even notice you were using `gcc` instead of `g++` and I even used that in my own example. Of course, `gcc` only compiles C code, while `g++` compiles C++ code, and this library is in C++, not C.

**Comment by brunolnetto** [comment]
We are all educated idiots.

**Comment by brunolnetto** [comment]
I suggest to shrink the README content and add the command provided by @AlexanderSerov on [his commment](https://github.com/bshoshany/thread-pool/issues/39#issuecomment-1101651120).
