### ISSUE TITLE
[REQ] Thread busy loop optimization

### ISSUE THREAD

**Issue by zeroxia** [bshoshany/thread-pool#40]
In the `void worker()` function, when no task is available, it just calls `sleep_or_yield()`, which means all threads are frequently awaken and then go to sleep again (Like 1000 times per second). I think this is suboptimal, why not put a thread to sleep with condition variable?

**Comment by Liam0205** [comment]
Same idea, thus the project: https://github.com/Liam0205/toy-threadpool

**Comment by bshoshany** [comment]
Thanks for the suggestion. This has already been implemented in v3.0.0 of the library, which will be released in a few weeks.

**Comment by bshoshany** [comment]
Update: v3.0.0 is ready, it will be released in the next few days!

**Comment by AlexanderSerov** [comment]
@bshoshany Hi!
We switched to current thread pool form [this](https://github.com/progschj/ThreadPool) one, which prove to be buggy. After switch we notice significant performance regression while running tests on big amount of iterations of running tasks. So we are very exited to test coming release which expected to improve performance. Is ETA known?

**Comment by bshoshany** [comment]
The code is actually ready, I just need to finish updating the `README.md` file. The new release should be uploaded tomorrow, maybe even today if I manage to find the time...

**Comment by bshoshany** [comment]
I just uploaded the new release :)
