### ISSUE TITLE
[BUG] VS 2022 Win32 crash (compiler bug ?)

### ISSUE THREAD

**Issue by Nelson-numerical-software** [bshoshany/thread-pool#41]
**Describe the bug**

This simple code crashes with VS 2022 win32 target BUT it works with same compiler x64

![image](https://user-images.githubusercontent.com/23081266/169375341-8beb671d-b631-4b0d-9100-7b980d7a6bbb.png)

**Minimal working example**

```cpp
    thread_pool pool;
```

"A breakpoint statement (__debugbreak() statement or similar call) was executed in NelSon-gui.exe."

**Behavior**

Code works perfectly on x64 target but same crashs on win32 target

**System information**

* CPU model, architecture, # of cores and threads: AMD 4800H
* Operating system: Windows 10
* Name and version of C++ compiler: VS 2022 Version 17.2.1
* Full command used for compiling, including all compiler flags:
```
/permissive- /MP /ifcOutput "Release\" /GS /GL /analyze- /W3 /Gy /Zc:wchar_t /I"D:\Developpements\Github\nelson\modules/os_functions/src/include" /I"D:\Developpements\Github\nelson\modules/dynamic_link/src/include" /I"D:\Developpements\Github\nelson\modules/characters_encoding/src/include" /I"D:\Developpements\Github\nelson\modules/i18n/src/include" /I"D:\Developpements\Github\nelson\modules/interpreter/src/include" /I"D:\Developpements\Github\nelson\modules/types/src/include" /I"D:\Developpements\Github\nelson\modules/api_nelson/src/include" /I"D:\Developpements\Github\nelson\modules/stream_manager/src/include" /I"D:\Developpements\Github\nelson\modules/error_manager/src/include" /I"D:\Developpements\Github\nelson\modules/nelson_manager/src/include" /I"D:\Developpements\Github\nelson\../NelSon-thirdparty-Win32/Boost" /Zi /Gm- /O2 /sdl /Fd"Release\vc143.pdb" /Zc:inline /fp:precise /D "WIN32" /D "NDEBUG" /D "_WINDOWS" /D "_USRDLL" /D "NLSOS_FUNCTIONS_EXPORTS" /D "_WINDLL" /D "_UNICODE" /D "UNICODE" /errorReport:prompt /WX- /Zc:forScope /Gd /Oy- /Oi /MD /openmp /std:c++17 /FC /Fa"Release\" /EHsc /nologo /Fo"Release\" /Fp"Release\libnlsOs_functions.pch" /diagnostics:column 
```
* Thread pool library version: github master

(Please note that only the latest version of the thread pool library is supported.)

**Additional information**

No sure but it must be more a compiler bug that code :(
Reported for feedback and eventualy a workaround

**Comment by Nelson-numerical-software** [comment]
With win32 target, if I do:
`thread_pool pool(1);` to `thread_pool pool(5);`  it works
But  with 6 to 16 (AMD 4800H 8 cores - 16 threads) it crashes

Same code and same tests, it works `thread_pool pool(1);` to `thread_pool pool(16);`

**Comment by bshoshany** [comment]
Sorry, I don't know what the problem is :( On my computer with the same compiler (VS 2022 Version 17.2.1) it works just fine for both x64 and x86 targets. Have you tried other compilers?

**Comment by Nelson-numerical-software** [comment]
Maybe could you create a CI with win32 build.
I reproduce again with trouble  (3.2.0 and VS 17.2.6 on 3 windows 11 pc  64bit with 32 bit build)
It is difficult to detect numbers of threads to create without to have this exception on different platform

**Comment by bshoshany** [comment]
1. Which version of MSVC are you using (not VS, but the compiler itself)? 
2. Which version of the Windows SDK are you using?
3. Have you tried compiling with GCC or Clang instead?

**Comment by Nelson-numerical-software** [comment]
"1Which version of MSVC are you using (not VS, but the compiler itself)?
MSVC v143 VS 2022 C++x64/x86 build tools

"Which version of the Windows SDK are you using?"
sdk used : Kit sdk Windows 10 10.01.19041.0

"3.Have you tried compiling with GCC or Clang instead?"
- Clang and GCC code are OK (32 and 64 bits platforms)


win64 with same compiler is OK (same code)

same binary, target win32, same .exe :
- OK: Works on 32 bits with intel cpu i7500 (win10 64 bits)   (2 core 4 threads)
- KO: windows 11 64 bits intel cpu  i5 10500t (6 cores 12 threads)
catched error "resource unavailable try again: resource unavailable try again"
- KO: windows 11 64 bits AMD 4800H (8 core 16 threads)
- KO: windows 11 64 bits AMD 5600(8 core 16 threads)
- KO: windows 11 64 bits AMD 3900X (12 core 24 threads)

on these same pcs 64 bits target works.

I need to reduce code to test easier and to be sure that it is not my fault.

Very strange behavior that it works with 64 bits target and not with 32 bits

I will give more feedback quickly

**Comment by bshoshany** [comment]
1. Can you update to the latest Windows 10 SDK (10.0.20348.0) and check again?
2. When you compile `BS_thread_pool_test.cpp`, does it work? If it does, then the problem is with your specific code, not with the library itself.

**Comment by Nelson-numerical-software** [comment]
- same trouble with Windows 10 SDK (10.0.20348.0)
- BS_thread_pool_test.cpp works perfectly.
- I reduced code, trouble seems to come of others dependencies.
If MKL and OpenMP uses only one computational thread (OMP_THREADS=1 env var.), code using thread-pool works as expected with 8 threads on Windows 32 bits.
Windows 32 bits supports is near to be dead. So It is no a major trouble, I will use only 4 threads or less on Win32

Thanks for your support and your library :)

If you add a section on readme with list of projects using library, you can add:
https://github.com/Nelson-numerical-software/nelson/blob/master/CITATION.cff
https://nelson-numerical-software.github.io/nelson-website/PARALLEL.html

**Comment by bshoshany** [comment]
If `BS_thread_pool_test.cpp` works perfectly, then the problem is most likely with another library, or with something in your code itself. Since you're the only user who has this problem and I cannot reproduce it, I'm afraid there's nothing more I can do to help with this :(

I'm glad you like the library and that you found it useful! I'll consider adding links to projects that use it.
