### ISSUE TITLE
Potential zero threads

### ISSUE THREAD

**Issue by TLCFEM** [bshoshany/thread-pool#51]
https://github.com/bshoshany/thread-pool/blob/9d43f5d05d11835ec027ae0679f8cd8a1a87e9cb/BS_thread_pool.hpp#L100

[`std::thread::hardware_concurrency()`](https://en.cppreference.com/w/cpp/thread/thread/hardware_concurrency) may return 0. So when constructed as `thread_pool()`, `thread_count` may be initialised to 0. `thread_count(thread_count_ > 1 ? thread_count_ : 1` may be safer.

**Comment by bshoshany** [comment]
Thanks, I will fix this in the next release.
