### ISSUE TITLE
Type concurrency_t is just unsigned integer on C++17 compliant platform. Why it was introduced?

### ISSUE THREAD

**Issue by nyx191** [bshoshany/thread-pool#54]
You don't need `concurrency_t` or even `BS::concurrency_t`, you can just use `unsigned`.
Please correct me if I'm wrong.

**Comment by nyx191** [comment]
Ah, ok, that will break all uses of library, but in case of incompatible changes in future versions anyway...

**Comment by bshoshany** [comment]
I wrote about this in [`CHANGELOG.md`](https://github.com/bshoshany/thread-pool/blob/master/CHANGELOG.md):

> Added a new type, `BS::concurrency_t`, equal to the return type of `std::thread::hardware_concurrency()`. This is probably pointless, since the C++ standard requires this to be `unsigned int`, but it seems to me to make the code slightly more portable, in case some non-conforming compiler chooses to use a different integer type.
