### ISSUE TITLE
[Question] How to retrieve pointer function of functions available in thread pool list ?

### ISSUE THREAD

**Issue by Nelson-numerical-software** [bshoshany/thread-pool#55]
Again a question, sorry :)

I try to developp parfeval equivalent feature using thread-pool ;)
https://pbs.twimg.com/media/FVeuU0gVsAIjxEL?format=jpg&name=small
https://pbs.twimg.com/media/FSN0xl_X0AEt9hJ?format=jpg&name=900x900

Currently I manage another list with all functions pointer submitted. But maintains another list is difficult (synchro).

How can I do this without maintaining another list with submitted functions ?

```
f function evaluate fptr(args)

threadpool pool;
pool.submit(f, fptr1, args)
pool.submit(f, fptr2, args)
pool.submit(f, fptr3, args)
```

I would like to have list fptr1, ... fptr3 available in thread_pool and also two lists with running and  queued functions 
```
std::vector<fptr> runningsFunctions = pool.getRunningThreads()
std::vector<fptr> queuedFunctions = pool.getQueuedThreads()
std::vector<fptr> poolFunctions = pool.getAllThreads()
```

Ideas are welcome (Thanks for your help)

**Comment by bshoshany** [comment]
Happy to help, but I need more information. What exactly are you trying to do? (I'm not familiar with your system.) And why do you need function pointers to do it?
