### ISSUE TITLE
is it possible to parallel compute nested loops ? 

### ISSUE THREAD

**Issue by chromafunk** [bshoshany/thread-pool#60]
```
        BS::thread_pool pool(10);
        pool.parallelize_loop(0, cwts.eventOfEvents.at(0).size(),
                              [&cwts,&hist](const int a, const int b)
                              {
                                  for (int t = 0; t < cwts.eventOfEvents.size(); ++t)
                                  {

                                      for (int i = a; i < b; ++i)
                                      {

                                          hist->Fill(i, t, cwts.eventOfEvents[t][i]);
                                      }
                                  }
                              })
            .wait();
```

right now I'm doing this, which is attempting to read the inner arrays in parallel. Is it possible to make it do both loops ? 

Thanks !

**Comment by bshoshany** [comment]
Hi @chromafunk, the best way to parallelize nested loops strongly depends on what the loops actually do and how they handle resources. So this isn't something the thread pool can do automatically, it's up to you as the programmer to decide whether you want to parallelize the inner or outer loop (or even some combination of both) based on what works best in your particular case.

One thing to keep in mind is that if the loop accesses the same data at different iterations, then you should make sure one parallel block won't interfere with another block which might be running at the same time.

**Comment by chromafunk** [comment]
Thank you for the tips ! 

I have been using this library for a while and it's great :)

**Comment by bshoshany** [comment]
No problem! I'm glad you like it :)
