### ISSUE TITLE
Add Github CI running tests

### ISSUE THREAD

**Issue by Nelson-numerical-software** [bshoshany/thread-pool#63]
A good practice is to run test on CI
each Platform officially supported could be tested.

No complaints, just a quality approach.
Thanks for this really good library

**Comment by bshoshany** [comment]
Thanks for the suggestion! I think these automated tests are meant for a repository where multiple people commit code often and you need to check that the code still runs after each commit. However, with this library, I only use GitHub as a platform to post my code every once in a while after editing it locally, and get bug reports and suggestions from users. Before I post each new release, I test it thoroughly myself on several systems. Therefore, GitHub CI is not useful for me for this specific project.
