### ISSUE TITLE
Avoiding multiple declaration error at compile time

### ISSUE THREAD

**Issue by RemyBorius** [bshoshany/thread-pool#66]
First, thanks a lot for this library, it's really useful and easy to use ! 

My problem is that if I want to use the library in more than one .cpp file (aka I need to include the lib's hpp in more than one cpp file), I inevitably have a multiple declaration error at compile time because of the .hpp defining the functions and stuff.

(if the lib's hpp is included in a header (foo.h), there is as much multiple declaration as the foo.h is included)

Maybe i just miss the good use of the lib, but if not it could be usefull to have a cpp/h version that split definition and declaration to avoid this problem.

Regards

**Comment by bshoshany** [comment]
Thanks for opening this issue, @RemyBorius!

Which version are you using? I think you are referring to #64, which was fixed in v3.3.0 (release yesterday).

**Comment by RemyBorius** [comment]
Ho, didn't see that, have the one from last week.

Gonna check that soon

**Comment by bshoshany** [comment]
Great! Let me know if you are still having issues.

**Comment by RemyBorius** [comment]
It's fixed ! 
I need to read more carefully the other issue reports adding one more ^^'

**Comment by bshoshany** [comment]
Sounds good, and no worries! :)
