### ISSUE TITLE
Not deallocating memory

### ISSUE THREAD

**Issue by ghoshbishakh** [bshoshany/thread-pool#67]
I am using `push_task` and `wait_for_tasks` in order to submit lambdas to the thread pool.
However, after `wait_for_tasks`, or even after calling `reset` the memory is not freed. If I submit more tasks then the memory keeps on increasing thus implying a leak.

I tried adding `std::queue<std::function<void()>>().swap(tasks);` to free the task queue but no improvement.

How to fix this issue?

I am doing something like this:

```
pool.push_task([&A, &B, &C, i]{
            A[i]  = B[i] + C[i];
            });

```

**Comment by bshoshany** [comment]
Thanks for opening the issue! However, there shouldn't be any memory leaks in the thread pool class, since I only use STL containers and smart pointers. If there's a leak, then it must be due to something in your own code.
