### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by RemyBorius** [bshoshany/thread-pool#68]
**Describe the bug**

It might not be considered as a bug, but my personal usage of the timer helper class doesn't match with his implementation, so I wanted to share it, maybe you'll want to adapt or not :
* The timer helper class is rebooted to zero at each start/stop. It cannot be used to sum times of different blocks of code
* I personally like to use this class to compute the time spent into a part of code that is parallelized, to know the actual "real computation time" among all the thread, I use it like this (see behind) :   

**Minimal working example**

```cpp
BS::timer timer;             //defined as a global variable 
myFunction {                      // this one runs in multiple threads
  timer.start();
  doStuff();
  timer.stop();
  return;
}
```
Then I can print the timer value when all the threads are over. Easy.
For this to work properly, I just need to change `=` by `+=` in the stop() function, like this

```cpp
        void stop()
        {
            elapsed_time += std::chrono::steady_clock::now() - start_time;
        }
```

This small change can make the timer more versatile, but if doing so it might also be useful to add a function to manually reboot the timer to zero like : 

```cpp
        /**
     * @brief reboot the timer to zero
         */
        void reboot()
        {
            elapsed_time = std::chrono::duration<double>::zero();
        }
```

**Comment by bshoshany** [comment]
Thanks for opening this issue. The `timer` helper class is just a super-simple tool to measure a single duration of time. You are welcome to  extend it as you see fit for your own use, but the version bundled with this package was created solely for the sake of the package's own performance tests, and at the moment there is no need for any additional functionality.
