### ISSUE TITLE
Task creation error with function that have specific parameters.

### ISSUE THREAD

**Issue by JiayunLi-3E8** [bshoshany/thread-pool#69]
**Describe the bug**

There is a member function of another library's class as a parameter, and an error is reported when it is passed as a parameter to push_tasks.

**Minimal working example**

[test.zip](https://github.com/bshoshany/thread-pool/files/9349155/test.zip)

**Behavior**

[main] Building folder: test 
[main] The folder containing the CMake cache is missing. The cache will be regenerated.
[main] Configuring folder: test 
[proc] Executing command: /usr/bin/cmake --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_C_COMPILER:FILEPATH=/home/jiayunli/x-tools/armv6-rpi-linux-gnueabihf/bin/armv6-rpi-linux-gnueabihf-gcc -DCMAKE_CXX_COMPILER:FILEPATH=/home/jiayunli/x-tools/armv6-rpi-linux-gnueabihf/bin/armv6-rpi-linux-gnueabihf-g++ -S/home/jiayunli/Documents/test -B/home/jiayunli/Documents/test/build -G "Unix Makefiles"
[cmake] Not searching for unused variables given on the command line.
[cmake] -- The C compiler identification is GNU 10.3.0
[cmake] -- The CXX compiler identification is GNU 10.3.0
[cmake] -- Detecting C compiler ABI info
[cmake] -- Detecting C compiler ABI info - done
[cmake] -- Check for working C compiler: /home/jiayunli/x-tools/armv6-rpi-linux-gnueabihf/bin/armv6-rpi-linux-gnueabihf-gcc - skipped
[cmake] -- Detecting C compile features
[cmake] -- Detecting C compile features - done
[cmake] -- Detecting CXX compiler ABI info
[cmake] -- Detecting CXX compiler ABI info - done
[cmake] -- Check for working CXX compiler: /home/jiayunli/x-tools/armv6-rpi-linux-gnueabihf/bin/armv6-rpi-linux-gnueabihf-g++ - skipped
[cmake] -- Detecting CXX compile features
[cmake] -- Detecting CXX compile features - done
[cmake] -- Configuring done
[cmake] -- Generating done
[cmake] -- Build files have been written to: /home/jiayunli/Documents/test/build
[build] Starting build
[proc] Executing command: /usr/bin/cmake --build /home/jiayunli/Documents/test/build --config Debug --target all -j 10 --
[build] [ 50%] Building CXX object CMakeFiles/test.dir/main.cpp.o
[build] In file included from /home/jiayunli/Documents/test/main.cpp:2:
[build] /home/jiayunli/Documents/test/BS_thread_pool.hpp: In instantiation of 'void BS::thread_pool::push_task(F&&, A&& ...) [with F = void (*)(sockpp::stream_socket_tmpl<sockpp::inet_address>); A = {sockpp::stream_socket_tmpl<sockpp::inet_address>}]':
[build] /home/jiayunli/Documents/test/main.cpp:15:39:   required from here
[build] /home/jiayunli/Documents/test/BS_thread_pool.hpp:427:31: error: conversion from 'std::_Bind_helper<false, void (*)(sockpp::stream_socket_tmpl<sockpp::inet_address>), sockpp::stream_socket_tmpl<sockpp::inet_address> >::type' to non-scalar type 'std::function<void()>' requested
[build]   427 |         std::function<void()> task_function = std::bind(std::forward<F>(task), std::forward<A>(args)...);
[build]       |                               ^~~~~~~~~~~~~
[build] make[2]: *** [CMakeFiles/test.dir/build.make:76：CMakeFiles/test.dir/main.cpp.o] 错误 1
[build] make[1]: *** [CMakeFiles/Makefile2:83：CMakeFiles/test.dir/all] 错误 2
[build] make: *** [Makefile:91：all] 错误 2
[build] Build finished with exit code 2

**System information**

* CPU model, architecture, # of cores and threads:
  Intel(R) Core(TM) i5-8300H,x86_64 , 4 cores, 8 threads
* Operating system:
  ArchLinux
* Name and version of C++ compiler:
  gcc 10.3 -- armv6-rpi-linux-gnueabihf
* Full command used for compiling, including all compiler flags:
 In configuration of cmake.
* Thread pool library version:
  v3.3.0 (2022-08-03)

**Comment by bshoshany** [comment]
I'm not familiar with this library, but it looks like the problem is that `sockpp::tcp_socket` has a deleted copy constructor. Therefore the task cannot be stored in the queue, because `std::function` must be `CopyConstructible`.  An easy solution is to wrap the task in a lambda:

```cpp
pool.push_task([&] { handle(std::move(ts)); });
```

Let me know if that works!

**Comment by JiayunLi-3E8** [comment]
For the example I submitted, your approach worked perfectly. But because my actual project situation is more complicated than that one, this method will cause objects to be lost, so I changed the usage of another library to bypass this problem. However, I think it would be better if your method of library could accept non-copyable objects as parameters, and hope you can solve it. 👍

**Comment by bshoshany** [comment]
Perhaps this could be resolved in C++23 with [std::move_only_function](https://en.cppreference.com/w/cpp/utility/functional/move_only_function), which will be able to accept a non-`CopyConstructible` object. Until then, I think passing a shared pointer to the object, instead of the object itself, might allow you to do what you want.

**Comment by JiayunLi-3E8** [comment]
Thanks for your suggestion. I will try to use this way when I have a similar problem again.
