### ISSUE TITLE
[BUG] libc++abi: terminating with uncaught exception of type std::__1::system_error: mutex lock failed: Invalid argument

### ISSUE THREAD

**Issue by alexiagaray** [bshoshany/thread-pool#79]
**Describe the bug**

Code working but get  error mutex after all operations

**Minimal working example**

0 tasks total, 0 tasks running, 0 tasks queued.
1 tasks total, 0 tasks running, 1 tasks queued.
2 tasks total, 1 tasks running, 1 tasks queued.
3 tasks total, 1 tasks running, 2 tasks queued.
4 tasks total, 1 tasks running, 3 tasks queued.
3 tasks total, 0 tasks running, 3 tasks queued.
2 tasks total, 0 tasks running, 2 tasks queued.
1 tasks total, 1 tasks running, 0 tasks queued.
libc++abi: terminating with uncaught exception of type std::__1::system_error: mutex lock failed: Invalid argument

```cpp
void taskMainLogic (std::string listLine1, std::string listLine2)
{
     .....
}

int main(int argc, const char * argv[]) {
BS::thread_pool pool(2);
for (int k = 0; k < list.size(); k++)
{
        pool.push_task(taskMainLogic, list[k], list2[std::rand() % list2.size()]
}
}
```

**Behavior**

**System information**

* CPU model, architecture, # of cores and threads: Macbook pro m1 2020 (arm64)
* Operating system: MACOS
* Name and version of C++ compiler:  Apple clang version 13.1.6 (clang-1316.0.21.2.5)
* Full command used for compiling, including all compiler flags: c++ main.cpp curly.cpp -o main -lcurl --std=c++17 && ./main
* Thread pool library version: last

(Please note that only the latest version of the thread pool library is supported.)

**Additional information**

Include any additional information here.

**Comment by bshoshany** [comment]
Thanks for opening this issue. However, I cannot reproduce this bug, because your example is missing the body of the function `taskMainLogic()`. A "minimal working example" means stand-alone code that I can run as-is on my own system to reproduce the bug. Please provide a working example so that I can investigate further.

**Comment by alexiagaray** [comment]
```cpp

void monitor_tasks(BS::thread_pool&pool)
{
    BS::synced_stream sync_out;
    sync_out.println(pool.get_tasks_total(), " tasks total, ", pool.get_tasks_running(), " tasks running, ", pool.get_tasks_queued(), " tasks queued.");
}

bool taskMainLogic (std::string list1, std::string list2)
{
  // with this code, it also gives an error about mutex
   return true;
}

int main(int argc, const char * argv[]) {
    std::vector<std::string> list;
    std::vector<std::string> list2;
    bool resultList1 = getFileContent("list.txt", list); // ["abc","edf"]
    bool resultList2 = getFileContent("list2.txt", list2); // ["000","001"]
    BS::synced_stream sync_out;
    BS::thread_pool pool(2);
    for (int k = 0; k < list.size(); k++)
        {
           monitor_tasks(pool);
           pool.push_task(taskMainLogic, list[k], list2[std::rand() % list2.size()])
        }
       // all task done.
        pool.wait_for_tasks();
        return 0;
       // here 
}
```

0 tasks total, 0 tasks running, 0 tasks queued.
1 tasks total, 0 tasks running, 1 tasks queued.
2 tasks total, 1 tasks running, 1 tasks queued.
3 tasks total, 1 tasks running, 2 tasks queued.
4 tasks total, 1 tasks running, 3 tasks queued.
5 tasks total, 1 tasks running, 4 tasks queued.
6 tasks total, 1 tasks running, 5 tasks queued.
6 tasks total, 1 tasks running, 5 tasks queued.
libc++abi: terminating with uncaught exception of type std::__1::system_error: mutex lock failed: Invalid argument
zsh: abort      ./main

perhaps the problem is due to the fact that my macbook is on an m1 chip

The code works, but this error occurs exactly after all the operations of the cycle at the end of the work

**Comment by bshoshany** [comment]
Again, I cannot run your code because the function `getFileContent()` is missing!

Please provide a **WORKING** example that I can literally copy, paste, compile, and run without guessing what the program is supposed to do.

If you do not provide a working example in your next comment, I will close this issue.

**Comment by alexiagaray** [comment]
> Again, I cannot run your code because the function `getFileContent()` is missing!
> 
> Please provide a **WORKING** example that I can literally copy, paste, compile, and run without guessing what the program is supposed to do.
> 
> If you do not provide a working example in your next comment, I will close this issue.

okay, copy + c / copy + v for u



```cpp
#include <iostream>
#include <fstream>
#include <string>
#include <vector>
#include "BS_thread_pool.hpp"
#include <algorithm>
#include <exception>
#include "curly.hpp"
#include <curl/curl.h>
#include "json.hpp"


namespace net = curly_hpp;
using json = nlohmann::json;

net::performer performer;

size_t WriteCallback(char *contents, size_t size, size_t nmemb, void *userp)
{
    ((std::string*)userp)->append((char*)contents, size * nmemb);
    return size * nmemb;
};

bool Request (std::string url)
{
    return true;
};


bool getFileContent(std::string fileName, std::vector<std::string> & vecOfStrs)
{
    std::ifstream in(fileName.c_str());

    if (!in)
    {
        std::cerr << "Cannot open the File: "<<fileName<<std::endl;
        return false;
    }

    std::string str;
    while (std::getline(in, str))
    {
        if(str.size() > 0)
            vecOfStrs.push_back(str);
    }
    in.close();
    return true;
};

bool taskMainLogic (std::string list1String, std::string list2String)
{
    return true;
};

void monitor_tasks(BS::thread_pool&pool)
{
    BS::synced_stream sync_out;
    sync_out.println(pool.get_tasks_total(), " tasks total, ", pool.get_tasks_running(), " tasks running, ", pool.get_tasks_queued(), " tasks queued.");
}

int main(int argc, const char * argv[]) {
    std::vector<std::string> list;
    std::vector<std::string> list2;
    bool resultList1 = getFileContent("list1.txt", list);
    bool resultList2 = getFileContent("list2.txt", list2);
    BS::synced_stream sync_out;
    BS::thread_pool pool(2);
    for (int k = 0; k < list.size(); k++)
        {
           monitor_tasks(pool);
           pool.push_task(taskMainLogic, list[k], list2[std::rand() % list2.size()]);
        }
       // all task done.
        pool.wait_for_tasks();
        return 0;
};
```
curly.hpp - https://github.com/BlackMATov/curly.hpp
json.hpp - https://github.com/nlohmann/json
[curlyAndJSON.zip](https://github.com/bshoshany/thread-pool/files/9436003/curlyAndJSON.zip)

[list1.txt](https://github.com/bshoshany/thread-pool/files/9435996/list1.txt)
[list2.txt](https://github.com/bshoshany/thread-pool/files/9435998/list2.txt)

Build argument - c++ main.cpp curly.cpp -o main -lcurl --std=c++17 && ./main

**Comment by alexiagaray** [comment]
Oh, damn, problem with net::performer performer; on global scope

**Comment by bshoshany** [comment]
Thank you for the working code example! I'm glad you were able to resolve the issue.
