### ISSUE TITLE
number of tasks > cores [documentation]

### ISSUE THREAD

**Issue by pha377** [bshoshany/thread-pool#87]
You mostly identify number of tasks with number of cores, but there are a lot of tasks that could have a lot of idle time, like a websocket client or server, file/network operations, etc.

**Comment by bshoshany** [comment]
Thanks for opening this issue, @pha377! The purpose of the documentation is only to teach the basics of how to use this library, not to teach how to do multithreading in general, which is beyond the scope of the documentation.
