### ISSUE TITLE
C++14 version 

### ISSUE THREAD

**Issue by 3manifold** [bshoshany/thread-pool#91]
Hi, is there a plan/macro for supporting c++14? Thanks in advance

**Comment by bshoshany** [comment]
Sorry, unfortunately there is no plan to backport this library to C++14.

**Comment by 3manifold** [comment]
Thank you for your reply. Is there a good quality open-source thread pool you would suggest?

**Comment by bshoshany** [comment]
To be honest, I'm not too familiar with any other thread pool libraries, since in my own software I have only ever used this one :(
